version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: not_there.wdl
   - subclass: WDL
     primaryDescriptorPath: goleft_functions.wdl
     testParameterFiles:
         - goleft_terra.json
